auction/auth.py
from flask import Blueprint, session, redirect, url_for, render_template, flash
from .forms import LoginForm, RegisterForm
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, logout_user, login_required
from .models import User

authentication_blueprint = Blueprint('authentication', __name__, url_prefix='/authentication')

#Login Blueprint
@authentication_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if login_form.validate_on_submit():
        # grab all data from form
        username = login_form.user_name.data
        pwd = login_form.password.data
        # attempt to grab existing user
        u = User.query.filter_by(name=username).first()
        if u is None:
            error="Incorrect username or password."
        # if exists, compare passwords
        elif not check_password_hash(u.password_hash, pwd):
            error="Incorrect username or password."
        # if match, login
        if error is None:
            # if error is none, success
            login_user(u)
            session['email'] = login_form.user_name.data
            return redirect(url_for('main.index'))
        else:
            flash(error, 'danger')
            return redirect(url_for('authentication.login'))
    return render_template('authentication/login.html', form=login_form)

#Register Blueprint
@authentication_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        # grab all data from form
        username = register_form.user_name.data
        email = register_form.email_id.data
        pwd = register_form.password.data
        contact = register_form.contact_no.data
        address = register_form.address.data
        # check if username already exists
        u = User.query.filter_by(name=username).first() # returns user object or NONE
        if u:
            flash('This username already exists', 'danger')
            return redirect(url_for('authentication.register', form=register_form))
        # if username unique, create new user
        pwd_hash = generate_password_hash(pwd)
        new_user = User(name=username, emailid=email, password_hash=pwd_hash, contactno=contact, address=address)

        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.index'))
    else:
        return render_template('authentication/register.html', form=register_form)

#Logout Blueprint
@authentication_blueprint.route('/logout')
def logout():
    print(session)
    logout_user()
    session.clear()
    return render_template('authentication/logout.html')

auction/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    <title>Phone Auction</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <!--NAVIGATION-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-top border-bottom border-dark">
        <a class="navbar-brand" href="{{url_for('main.index')}}"><img
                src="https://pngimg.com/uploads/phone/phone_PNG48927.png" width="30" height="30"
                class="d-inline-block align-top mr-2" alt="">
            Phone Auctions
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('listing.create')}}">Create Listing</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{url_for('listing.mylistings')}}">My Listings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('listing.listings')}}">Listings</a>
                </li>
                {% if session['email'] %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.watchlist')}}">Watchlist</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav mr-3">
                {% if session['email'] %}
                <li class="nav-item">
                    <a class="nav-link">{{session['email']}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('authentication.logout')}}">Logout</a>
                </li>
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('authentication.login')}}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!--/NAVIGATION-->


    {% block content %}
    {% endblock %}

    <!--FOOTER-->
    <!-- Footer -->
    <footer class="page-footer font-small bg-dark mt-auto">
        <!-- Copyright -->
        <nav
            class="navbar navbar-expand-lg navbar-dark bg-dark border-top border-bottom border-dark justify-content-center">
            <a class="navbar-brand">
                Copyright 2020 @ PhoneAuctions.com
            </a>
        </nav>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <!--/FOOTER-->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>

auction/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <!--HEADER-->
    <header class="masthead overflow-hidden">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 text-center">
                    <h1 class="font-weight-light">Phone Auctions</h1>
                    <p class="lead">The best site for unique phone auctions.</p>
                </div>
            </div>
        </div>
    </header>
    <!--/HEADER-->



    <!--ROW 2-->
    <div class="row no-gutters m-2 ml-2 mb-2">
        <div class="col-md bg-dark pt-3 pl-3 pb-3 pr-3 mr-1 ml-1 mt-1 bg-image panel-height-4">
        </div>
        <div class="col-md bg-dark pt-3 pl-3 pb-3 pr-3 mr-1 ml-1 mt-1 panel-height-4">
            <h3 class="text-white mb-3">Categories</h1>
                <ul class="list-group">
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('listing.category')}}" method="post">
                            <button class="btn btn-link btn-anchor remove_link_colour" style="padding:0px; border:0px solid transparent;" type="submit" name="search" value="Apple">Apple</button>
                        </form>
                        <span class="badge badge-primary badge-pill">{{apple}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('listing.category')}}" method="post">
                            <button class="btn btn-link btn-anchor remove_link_colour" style="padding:0px; border:0px solid transparent;" type="submit" name="search" value="Google">Google</button>
                        </form>
                        <span class="badge badge-primary badge-pill">{{google}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('listing.category')}}" method="post">
                            <button class="btn btn-link btn-anchor remove_link_colour" style="padding:0px; border:0px solid transparent;" type="submit" name="search" value="Samsung">Samsung</button>
                        </form>
                        <span class="badge badge-primary badge-pill">{{samsung}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('listing.category')}}" method="post">
                            <button class="btn btn-link btn-anchor remove_link_colour" style="padding:0px; border:0px solid transparent;" type="submit" name="search" value="Sony">Sony</button>
                        </form>
                        <span class="badge badge-primary badge-pill">{{sony}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('listing.category')}}" method="post">
                            <button class="btn btn-link btn-anchor remove_link_colour" style="padding:0px; border:0px solid transparent;" type="submit" name="search" value="Oppo">Oppo</button>
                        </form>
                        <span class="badge badge-primary badge-pill">{{oppo}}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <form class="form-inline d-flex flex-nowrap" action="{{url_for('listing.category')}}" method="post">
                            <button class="btn btn-link btn-anchor remove_link_colour" style="padding:0px; border:0px solid transparent;" type="submit" name="search" value="All">All</button>
                        </form>
                        <span class="badge badge-primary badge-pill">{{allItems|length}}</span>
                    </li>
                </ul>
        </div>
        <div class="col-md bg-dark pt-3 pl-3 pb-3 pr-3 ml-1 mr-1 mt-1 panel-height-4">
            <h3 class="text-white mb-3">Recent Listings</h1>
                <ul class="list-group">
                    {% for item in items %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a class="remove_link_colour" href="{{url_for('listing.item', id=item.id)}}">{{item.name}}</a>
                        <div>
                            <span class="badge badge-success">${{item.curr_currency}}AU</span>
                            <span class="badge badge-primary badge-pill">{{item.bids|length}}</span>
                            {% if item.status == true %}
                            <span class="badge badge-success badge-pill">Ongoing</span>
                            {% else %}
                            <span class="badge badge-danger badge-pill">Closed</span>
                            {% endif %}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
        </div>
    </div>
    <!--/ROW 2-->
{% endblock %}

auction/templates/listings.html
{% extends 'base.html' %}


    {% block content %}
    <!--HEADER-->
    <header class="masthead overflow-hidden">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12 text-center">
                    <h1 class="font-weight-light">Live Listings</h1>
                </div>
            </div>
        </div>
    </header>
    <!--/HEADER-->

    <!--Row-->
    <div class="row no-gutters mt-2 mr-1 ml-2 mb-2">
        <div class="col-md bg-dark pt-3 pl-3 pr-3 ml-1 mt-1 justify-content-center">
            <div class="row">
                <div class="col-md-3">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Categories</span>
                        </div>
                        <select class="form-control" id="exampleFormControlSelect1">
                            <option>Apple</option>
                            <option>iPhone</option>
                            <option>Google</option>
                            <option>Samsung</option>
                            <option>Sony</option>
                            <option>Oppo</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row no-gutters ml-2 mb-2">
        <div class="col-md bg-dark pt-3 pl-3 pb-3 pr-3 mr-1 ml-1 mt-1 justify-content-center">
            <div class="row bg-white pt-2 ml-1 mr-1 border">
                <div class="col col-lg-2 mb-3">
                    <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                        class="mx-auto img-fluid min-vh-0">
                </div>
                <div class="col-lg-5 mx-auto">
                    <div class="row mx-1 mb-2">
                        <h1><a href = "{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                    </div>
                    <div class="row mx-1">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                        sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.
                    </div>
                </div>
                <div class="col-md">
                    <h2>Starting Bid</h2>
                    <h2><span class="badge badge-danger">$200AU</span></h2>
                    <h2>Current Bid</h2>
                    <h2><span class="badge badge-success">$800AU</span></h2>
                    <h2>Number of Bids</h2>
                    <h2><span class="badge badge-primary">131</span></h2>
                </div>
                <div class="col-lg text-center my-auto py-2">
                    <button type="button" class="btn btn-secondary btn-lg btn-block">Closed Listing
                    </button>
                    <button type="button" class="btn btn-secondary btn-lg btn-block"><a class="remove_link_colour"
                            href="{{url_for('main.watchlist')}}">Add to Watchlist</a>
                    </button>
                </div>
            </div>
            <div class="row bg-white pt-2 ml-1 mr-1 border">
                <div class="col col-lg-2 mb-3">
                    <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                        class="mx-auto img-fluid min-vh-0">
                </div>
                <div class="col-lg-5 mx-auto">
                    <div class="row mx-1 mb-2">
                        <h1><a href = "{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                    </div>
                    <div class="row mx-1">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                        sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.
                    </div>
                </div>
                <div class="col-md">
                    <h2>Starting Bid</h2>
                    <h2><span class="badge badge-danger">$200AU</span></h2>
                    <h2>Current Bid</h2>
                    <h2><span class="badge badge-success">$800AU</span></h2>
                    <h2>Number of Bids</h2>
                    <h2><span class="badge badge-primary">131</span></h2>
                </div>
                <div class="col-lg text-center my-auto py-2">
                    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                        data-target="#BidModal">Place Bid
                    </button>
                    <button type="button" class="btn btn-secondary btn-lg btn-block"><a class="remove_link_colour"
                            href="{{url_for('main.watchlist')}}">Add to Watchlist</a>
                    </button>
                </div>
            </div>
            <div class="row bg-white pt-2 ml-1 mr-1 border">
                <div class="col col-lg-2 mb-3">
                    <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                        class="mx-auto img-fluid min-vh-0">
                </div>
                <div class="col-lg-5 mx-auto">
                    <div class="row mx-1 mb-2">
                        <h1><a href = "{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                    </div>
                    <div class="row mx-1">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                        sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.
                    </div>
                </div>
                <div class="col-md">
                    <h2>Starting Bid</h2>
                    <h2><span class="badge badge-danger">$200AU</span></h2>
                    <h2>Current Bid</h2>
                    <h2><span class="badge badge-success">$800AU</span></h2>
                    <h2>Number of Bids</h2>
                    <h2><span class="badge badge-primary">131</span></h2>
                </div>
                <div class="col-lg text-center my-auto py-2">
                    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                        data-target="#BidModal">Place Bid
                    </button>
                    <button type="button" class="btn btn-secondary btn-lg btn-block"><a class="remove_link_colour"
                            href="{{url_for('main.watchlist')}}">Add to Watchlist</a>
                    </button>
                </div>
            </div>
            <div class="row bg-white pt-2 ml-1 mr-1 border">
                <div class="col col-lg-2 mb-3">
                    <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                        class="mx-auto img-fluid min-vh-0">
                </div>
                <div class="col-lg-5 mx-auto">
                    <div class="row mx-1 mb-2">
                        <h1><a href = "{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                    </div>
                    <div class="row mx-1">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                        ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                        sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                        est laborum.
                    </div>
                </div>
                <div class="col-md">
                    <h2>Starting Bid</h2>
                    <h2><span class="badge badge-danger">$200AU</span></h2>
                    <h2>Current Bid</h2>
                    <h2><span class="badge badge-success">$800AU</span></h2>
                    <h2>Number of Bids</h2>
                    <h2><span class="badge badge-primary">131</span></h2>
                </div>
                <div class="col-lg text-center my-auto py-2">
                    <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                        data-target="#BidModal">Place Bid
                    </button>
                    <button type="button" class="btn btn-secondary btn-lg btn-block"><a class="remove_link_colour"
                            href="{{url_for('main.watchlist')}}">Add to Watchlist</a>
                    </button>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}

auction/templates/mylistings.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
<!--HEADER-->
<header class="masthead overflow-hidden">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 text-center">
                <h1 class="font-weight-light">Create Your Own Listing</h1>
                <button type="button" class="btn btn-secondary btn-lg"><a href="{{url_for('main.create')}}" class="remove_link_colour">Create</a></button>
            </div>
        </div>
    </div>
</header>
<!--/HEADER-->

<div class="row no-gutters m-2 ml-2 mb-2">
    <div class="col-md bg-dark pt-3 pl-3 pb-3 pr-3 mr-1 ml-1 mt-1 justify-content-center">
        <div class="row bg-white pt-2 ml-1 mr-1 border">
            <div class="col col-lg-2 mb-3">
                <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                    class="mx-auto img-fluid min-vh-0">
            </div>
            <div class="col-lg-5 mx-auto">
                <div class="row mx-1 mb-2">
                    <h1><a href="{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                </div>
                <div class="row mx-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                    est laborum.
                </div>
            </div>
            <div class="col-md">
                <h2>Starting Bid</h2>
                <h2><span class="badge badge-danger">$200AU</span></h2>
                <h2>Current Bid</h2>
                <h2><span class="badge badge-success">$800AU</span></h2>
                <h2>Number of Bids</h2>
                <h2><span class="badge badge-primary">131</span></h2>
            </div>
            <div class="col-lg text-center my-auto py-2">
                <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                    data-target="#AllBids">View Bids
                </button>
                <button type="button" class="btn btn-danger btn-lg btn-block">Close Listing</button>
            </div>
        </div>
        <div class="row bg-white pt-2 ml-1 mr-1 border">
            <div class="col col-lg-2 mb-3">
                <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                    class="mx-auto img-fluid min-vh-0">
            </div>
            <div class="col-lg-5 mx-auto">
                <div class="row mx-1 mb-2">
                    <h1><a href="{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                </div>
                <div class="row mx-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                    est laborum.
                </div>
            </div>
            <div class="col-md">
                <h2>Starting Bid</h2>
                <h2><span class="badge badge-danger">$200AU</span></h2>
                <h2>Current Bid</h2>
                <h2><span class="badge badge-success">$800AU</span></h2>
                <h2>Number of Bids</h2>
                <h2><span class="badge badge-primary">131</span></h2>
            </div>
            <div class="col-lg text-center my-auto py-2">
                <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                    data-target="#AllBids">View Bids
                </button>
                <button type="button" class="btn btn-danger btn-lg btn-block">Close Listing</button>
            </div>
        </div>
        <div class="row bg-white pt-2 ml-1 mr-1 border">
            <div class="col col-lg-2 mb-3">
                <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                    class="mx-auto img-fluid min-vh-0">
            </div>
            <div class="col-lg-5 mx-auto">
                <div class="row mx-1 mb-2">
                    <h1><a href="{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                </div>
                <div class="row mx-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                    est laborum.
                </div>
            </div>
            <div class="col-md">
                <h2>Starting Bid</h2>
                <h2><span class="badge badge-danger">$200AU</span></h2>
                <h2>Current Bid</h2>
                <h2><span class="badge badge-success">$800AU</span></h2>
                <h2>Number of Bids</h2>
                <h2><span class="badge badge-primary">131</span></h2>
            </div>
            <div class="col-lg text-center my-auto py-2">
                <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                    data-target="#AllBids">View Bids
                </button>
                <button type="button" class="btn btn-danger btn-lg btn-block">Close Listing</button>
            </div>
        </div>
        <div class="row bg-white pt-2 ml-1 mr-1 border">
            <div class="col col-lg-2 mb-3">
                <img src="https://wolper.com.au/wp-content/uploads/2017/10/image-placeholder.jpg"
                    class="mx-auto img-fluid min-vh-0">
            </div>
            <div class="col-lg-5 mx-auto">
                <div class="row mx-1 mb-2">
                    <h1><a href="{{url_for('main.item')}}" class="remove_link_colour">Apple iPhone XR - 128GB - Factory New</a></h1>
                </div>
                <div class="row mx-1">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                    ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                    ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
                    sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                    est laborum.
                </div>
            </div>
            <div class="col-md">
                <h2>Starting Bid</h2>
                <h2><span class="badge badge-danger">$200AU</span></h2>
                <h2>Current Bid</h2>
                <h2><span class="badge badge-success">$800AU</span></h2>
                <h2>Number of Bids</h2>
                <h2><span class="badge badge-primary">131</span></h2>
            </div>
            <div class="col-lg text-center my-auto py-2">
                <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal"
                    data-target="#AllBids">View Bids
                </button>
                <button type="button" class="btn btn-danger btn-lg btn-block">Close Listing</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="AllBids" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">All Bids</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>User - Bid - Date</p>
                <p>User - Bid - Date</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}